name: Bot Workflow

on:
  - workflow_call

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    permissions:
      issues: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2.4.0 https://github.com/dependabot/fetch-metadata/commit/08eff52bf64351f401fb50d4972fa95b9f2c2d1b
        with:
          alert-lookup: true
          compat-lookup: true

      - name: Approve a PR
        shell: bash
        run: |
          gh pr checkout "$PR_URL"

          if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];then
            gh pr review --approve "$PR_URL"
          else
            echo "PR already approved, skipping additional approvals to minimize emails/notification noise.";
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        shell: bash
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}

  # TODO: #21 raise issue on failure for cron job
  # TODO: #22 update issue on job run failure
