# This workflow is managed by gh actions-lock.
# TODO: #21 raise issue on failure for job
# TODO: #22 update issue on job run failure
name: Bot Workflow

on:
  - workflow_call

permissions:
  contents: read

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    permissions:
      issues: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            codeload.github.com:443
            github.com:443
            objects.githubusercontent.com:443
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3.1.0
        with:
          alert-lookup: true
          compat-lookup: true
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Approve a PR
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          if [ "$(gh pr view "$PR_URL" --json reviewDecision -q .reviewDecision)" != "APPROVED" ];then
            gh pr review --approve "$PR_URL"
          else
            echo "PR already approved, skipping additional approvals to minimize emails/notification noise.";
          fi
      - name: Enable auto-merge for Dependabot PRs
        if: steps.metadata.outputs['update-type'] == 'version-update:semver-patch'
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr merge --auto --merge "$PR_URL"

  releaser:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Publish GitHub release
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          args=(--generate-notes --draft)
          if [[ "$TAG_NAME" == *-* ]]; then
            args+=(--prerelease)
          fi
          gh release create "$TAG_NAME" "${args[@]}"
