name: Continuos Integration

on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  bot:
    uses: ./.github/workflows/bot.yml
    permissions:
      issues: write
      pull-requests: write
      repository-projects: write

  trivy:
    uses: ./.github/workflows/trivy.yml
    permissions:
      contents: write
      id-token: write
      security-events: write

  scorecard:
    uses: ./.github/workflows/scorecard.yml
    permissions:
      id-token: write
      security-events: write

  # TODO: #17 Enable SonarQube Scan
  # sonarqube:
  #   uses: ./.github/workflows/sonarqube.yml
