name: Code Review

on:
  pull_request_target:
    types:
      - edited
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7  https://github.com/actions/checkout/commit/692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Lint Code Base
        uses: github/super-linter@12150456a73e248bdc94d0794898f94e23127c88 # v7.4.0 https://github.com/super-linter/super-linter/commit/12150456a73e248bdc94d0794898f94e23127c88
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ github.token }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH: false
          VALIDATE_DOCKERFILE_HADOLINT: false # FIXME: #18 superlinter not using .hadolint.yaml
          VALIDATE_KUBERNETES_KUBECONFORM: false # FIXME: #19 enable kubeconform
          VALIDATE_YAML_PRETTIER: false # FIXME: #20 ignore symlink

      # FIXME: #24 github_conf/branch_protection_rules.json -:-  fmt  Incorrect formatting, autoformat by running 'trunk fmt'
      # - name: Trunk Check
      #   uses: trunk-io/trunk-action@75699af9e26881e564e9d832ef7dc3af25ec031b # v1.2.4 https://github.com/trunk-io/trunk-action/commit/75699af9e26881e564e9d832ef7dc3af25ec031b
      #   with:
      #     post-annotations: true

  scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7  https://github.com/actions/checkout/commit/692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: GitGuardian Scan
        uses: GitGuardian/ggshield-action@d0d08872632cd1686ef9ffcaada2c8e9fcd7a541 # v1.41.0 https://github.com/GitGuardian/ggshield-action/commit/d0d08872632cd1686ef9ffcaada2c8e9fcd7a541
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}

      # TODO: #17 Enable SonarQube Scan
      # - name: SonarQube Scan
      #   uses: sonarsource/sonarqube-scan-action@2500896589ef8f7247069a56136f8dc177c27ccf # v5.2.0 https://github.com/SonarSource/sonarqube-scan-action/commit/2500896589ef8f7247069a56136f8dc177c27ccf
      #   env:
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    needs:
      - lint
      - scanning
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7  https://github.com/actions/checkout/commit/692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
          persist-credentials: false

      # FIXME: #16 HttpError: You do not have permission to create labels on this repository.
      # - name: Labeler
      #   uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0 https://github.com/actions/labeler/commit/8558fd74291d67161a8a78ce36a881fa63b766a9

      - name: Dependency Review
        uses: actions/dependency-review-action@da24556b548a50705dd671f47852072ea4c105d9 # v4.7.1 https://github.com/actions/dependency-review-action/commit/da24556b548a50705dd671f47852072ea4c105d9
        with:
          allow-ghsas: none
          allow-licenses: Apache-2.0,BSD-2-Clause,BSD-3-Clause,CC0-1.0,GPL-2.0,GPL-3.0,ISC,MIT,LGPL-3.0
          # deny-packages: empty
          # retry-on-snapshot-warnings-timeout: 120
          # retry-on-snapshot-warnings: true
          fail-on-severity: low

  assign:
    runs-on: ubuntu-latest
    needs: review
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7  https://github.com/actions/checkout/commit/692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Auto-assign
        uses: kentaro-m/auto-assign-action@f4648c0a9fdb753479e9e75fc251f507ce17bb7e # v2.0.0 https://github.com/kentaro-m/auto-assign-action/commit/f4648c0a9fdb753479e9e75fc251f507ce17bb7e
