# This workflow is managed by gh actions-lock.

name: Scorecard

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      score-card-token:
        type: string
        description: GitHub token for Scorecard to use for publishing results
      publish-results:
        type: boolean
        description: Whether to publish results to OpenSSF REST API
        default: true

jobs:
  analysis:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.20.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.deps.dev:443
            api.github.com:443
            api.osv.dev:443
            api.scorecard.dev:443
            fulcio.sigstore.dev:443
            github.com:443
            oss-fuzz-build-logs.storage.googleapis.com:443
            rekor.sigstore.dev:443
            tuf-repo-cdn.sigstore.dev:443
            www.bestpractices.dev:443
      - name: Checkout code
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run analysis
        uses: ossf/scorecard-action@v2.4.4
        with:
          publish_results: ${{ inputs['publish-results'] }}
          repo_token: ${{ inputs['score-card-token'] || github.token }}
          results_file: results.sarif
          results_format: sarif
      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          path: results.sarif
      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@v4.37.8
        with:
          sarif_file: results.sarif
