name: Scorecard

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      score-card-token:
        type: string
        description: GitHub token for Scorecard to use for publishing results
      publish-results:
        type: boolean
        description: Whether to publish results to OpenSSF REST API

jobs:
  analysis:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.deps.dev:443                                  # Dependency Track API
            api.github.com:443                                # GitHub API
            api.osv.dev:443                                   # OSV API
            api.scorecard.dev:443                             # Scorecard API
            fulcio.sigstore.dev:443                           # Fulcio CA
            github.com:443                                    # GitHub main site
            oss-fuzz-build-logs.storage.googleapis.com:443    # OSS-Fuzz build logs
            rekor.sigstore.dev:443                            # Rekor transparency log
            tuf-repo-cdn.sigstore.dev:443                     # Sigstore TUF repository CDN
            www.bestpractices.dev:443                         # Best Practices badge
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run analysis
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc # v2.4.4
        with:
          publish_results: true
          results_file: results.sarif
          results_format: sarif
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: results.sarif
      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@f0489abddd4e5e9dff53ed28a45b1d6f88978a1b # zizmor: ignore[ref-version-mismatch]
        with:
          sarif_file: results.sarif
