name: Scorecard

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      score-card-token:
        type: string
        description: GitHub token for Scorecard to use for publishing results
      publish-results:
        type: boolean
        description: Whether to publish results to OpenSSF REST API

jobs:
  analysis:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.deps.dev:443                                  # Dependency Track API
            api.github.com:443                                # GitHub API
            api.osv.dev:443                                   # OSV API
            api.scorecard.dev:443                             # Scorecard API
            fulcio.sigstore.dev:443                           # Fulcio CA
            github.com:443                                    # GitHub main site
            oss-fuzz-build-logs.storage.googleapis.com:443    # OSS-Fuzz build logs
            rekor.sigstore.dev:443                            # Rekor transparency log
            tuf-repo-cdn.sigstore.dev:443                     # Sigstore TUF repository CDN
            www.bestpractices.dev:443                         # Best Practices badge

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46 # v2.4.0
        with:
          publish_results: true
          results_file: results.sarif
          results_format: sarif

      - name: Upload artifact
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.2
        with:
          path: results.sarif

      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@b8efe4dc6ab6d31abe3ec159420d2a4916880800 # v3.26.6
        with:
          sarif_file: results.sarif
