# This workflow is managed by gh actions-lock.

name: Trivy

on:
  - workflow_call

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      id-token: write
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.20.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            check.trivy.dev:443
            dl.aquasec.com:443
            ghcr.io:443
            github.com:443
            mirror.gcr.io:443
      - name: Checkout code
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          exit-code: 1
          format: sarif
          hide-progress: false
          ignore-unfixed: true
          output: trivy-results.sarif
          scan-type: fs
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4.37.9
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          sarif_file: trivy-results.sarif
      - name: Run Trivy SBOM and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@v0.36.0
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          format: github
          github-pat: ${{ github.token }}
          image-ref: .
          output: dependency-results.sbom.json
          scan-type: fs
