name: Trivy

on:
  - workflow_call

permissions: read-all

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.1.7  https://github.com/actions/checkout/commit/692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@5681af892cd0f4997658e2bacc62bd0a894cf564 # v0.24.0 https://github.com/aquasecurity/trivy-action/commit/6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8
        with:
          exit-code: 1
          format: sarif
          hide-progress: false
          ignore-unfixed: true
          output: trivy-results.sarif
          scan-type: fs

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@b8efe4dc6ab6d31abe3ec159420d2a4916880800 # v3.26.6 https://github.com/github/codeql-action/commit/b8efe4dc6ab6d31abe3ec159420d2a4916880800
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        with:
          sarif_file: trivy-results.sarif

      - name: Run Trivy SBOM and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@5681af892cd0f4997658e2bacc62bd0a894cf564 # v0.24.0 https://github.com/aquasecurity/trivy-action/commit/6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        with:
          format: github
          github-pat: ${{ github.token }}
          image-ref: .
          output: dependency-results.sbom.json
          scan-type: fs
