# This workflow is managed by gh actions-lock.

name: Trivy

on:
  - workflow_call

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      id-token: write
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            check.trivy.dev:443
            dl.aquasec.com:443
            ghcr.io:443
            github.com:443
            mirror.gcr.io:443
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          exit-code: 1
          format: sarif
          hide-progress: false
          ignore-unfixed: true
          output: trivy-results.sarif
          scan-type: fs
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@2892aa5e19bbd11bc0cff5427e3b750a04d9e3c2 # v4.38.2
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          sarif_file: trivy-results.sarif
      - name: Run Trivy SBOM and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          format: github
          github-pat: ${{ github.token }}
          image-ref: .
          output: dependency-results.sbom.json
          scan-type: fs
